Adding also git version check and lowered required version.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,21 +1,26 @@
 #!/bin/bash
 
-# could use git rev-parse --abbrev-ref HEAD to get branch name
-git show origin/master:ProjectSettings/ProjectVersion.txt > ProjectSettings/LocalProjectVersion.txt
+# make sure local unity version matches current branch's remote revision
+BRANCH=$(git rev-parse --abbrev-ref HEAD)
+git show origin/$BRANCH:ProjectSettings/ProjectVersion.txt > ProjectSettings/LocalProjectVersion.txt
 
 # Unity version
 CURRENT_UNITY_PROJECT_VERSION=$(head -n 1 ProjectSettings/ProjectVersion.txt | cut -d ':' -f 2 | tr -d ' ')
 LOCAL_UNITY_PROJECT_VERSION=$(head -n 1 ProjectSettings/LocalProjectVersion.txt | cut -d ':' -f 2 | tr -d ' ')
 
 # git lfs version
-LOCAL_VER=$(git lfs env| awk -F ' ' 'FNR == 1 {print $1} ' | awk -F '/' '{print $2}')
-REQ_VER=2.10.0
+LOCAL_GIT_LFS_VERSION=$(git lfs env| awk -F ' ' 'FNR == 1 {print $1} ' | awk -F '/' '{print $2}')
+REQUIRED_MINIMUM_GIT_LFS_VERSION=2.10.0
+
+# git version
+LOCAL_GIT_VERSION=$(git --version | cut -d ' ' -f 3)
+REQUIRED_MININUM_GIT_VERSION=2.7.0
 
 # colors
 RED='\033[0;31m'
 BLACK="$(tput sgr0)"
 
-# compare version (pure Bash/Sh)
+# compare version 
 vercomp () {
     if [[ $1 == $2 ]]
     then
@@ -47,30 +52,51 @@ vercomp () {
     return 0
 }
 
-echo "*********************** PRE-COMMIT HOOK *********************************"
+echo "*************************************** PRE-COMMIT HOOK ********************************************"
 
+# if unity version is correct, then we also check for correct git and and git lfs version next
 if [  "$CURRENT_UNITY_PROJECT_VERSION" = "$LOCAL_UNITY_PROJECT_VERSION" ];  then
    echo -e "Local version and current Unity version are consistent: ${RED} $CURRENT_UNITY_PROJECT_VERSION ${BLACK}."
-   echo "*************************************************************************"
-
-    vercomp "$LOCAL_VER" "$REQ_VER"
+   echo "****************************************************************************************************"
+   
+    # check git lfs version
+    vercomp "$LOCAL_GIT_LFS_VERSION" "$REQUIRED_MINIMUM_GIT_LFS_VERSION"
     case $? in
         0) op='=';;
         1) op='>';;
         2) op='<';;
     esac
 
-
     if [[ ! $op != "<" ]]; then
-      echo -e "Local git lfs version does not satisfy minimum required version ${RED} $LOCAL_VER ${BLACK}(Have) < ${RED} $REQ_VER ${BLACK} (Required) ${BLACK}."
-      echo "*************************************************************************"
+      echo -e "Local git lfs version does not satisfy minimum required version ${RED} $LOCAL_GIT_LFS_VERSION ${BLACK}(Have) < ${RED} $REQUIRED_MINIMUM_GIT_LFS_VERSION ${BLACK} (Required) ${BLACK}."
+      echo "****************************************************************************************************"
       git stash 
       echo "Your changes have been stashed. Use git stash pop to retrieve (uncommited) changes."
       exit 1
     fi 
 
-      echo -e "Local git lfs version does satisfy minimum required version ${RED} $LOCAL_VER ${BLACK}(Have) >= ${RED} $REQ_VER ${BLACK} (Required) ${BLACK}."
-    echo "*************************************************************************"
+      echo -e "Local git lfs version does satisfy minimum required version ${RED} $LOCAL_GIT_LFS_VERSION ${BLACK}(Have) >= ${RED} $REQUIRED_MINIMUM_GIT_LFS_VERSION ${BLACK} (Required) ${BLACK}."
+      echo "****************************************************************************************************"
+
+   
+   # check git version
+    vercomp "$LOCAL_GIT_VERSION" "$REQUIRED_MININUM_GIT_VERSION"
+    case $? in
+        0) op='=';;
+        1) op='>';;
+        2) op='<';;
+    esac
+
+    if [[ ! $op != "<" ]]; then
+      echo -e "Local git version does not satisfy minimum required version ${RED} $LOCAL_GIT_VERSION ${BLACK}(Have) < ${RED} $REQUIRED_MINIMUM_GIT_VERSION ${BLACK} (Required) ${BLACK}."
+      echo "****************************************************************************************************"
+      git stash 
+      echo "Your changes have been stashed. Use git stash pop to retrieve (uncommited) changes."
+      exit 1
+    fi 
+
+      echo -e "Local git version does satisfy minimum required version ${RED} $LOCAL_GIT_VERSION ${BLACK}(Have) >= ${RED} $REQUIRED_MININUM_GIT_VERSION ${BLACK} (Required) ${BLACK}."
+      echo "****************************************************************************************************"
 
     exit 0
 else 
